// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WebsocketNonSystem.proto

package protobuf.proto;

public interface WebsocketNonSystemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kcwiki.msgtransfer.protobuf.WebsocketNonSystem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string module = 1;</code>
   */
  java.lang.String getModule();
  /**
   * <code>string module = 1;</code>
   */
  com.google.protobuf.ByteString
      getModuleBytes();

  /**
   * <code>string data = 2;</code>
   */
  java.lang.String getData();
  /**
   * <code>string data = 2;</code>
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
