// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WebsocketWrapper.proto

package protobuf.proto;

public final class WebsocketProto {
  private WebsocketProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kcwiki_msgtransfer_protobuf_Websocket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kcwiki_msgtransfer_protobuf_Websocket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026WebsocketWrapper.proto\022\033kcwiki.msgtran" +
      "sfer.protobuf\"\247\002\n\tWebsocket\022D\n\nproto_typ" +
      "e\030\001 \001(\01620.kcwiki.msgtransfer.protobuf.We" +
      "bsocket.ProtoType\022D\n\nproto_code\030\002 \001(\01620." +
      "kcwiki.msgtransfer.protobuf.Websocket.Pr" +
      "otoCode\022\025\n\rproto_payload\030\005 \001(\014\022\021\n\ttimest" +
      "amp\030\003 \001(\003\022\014\n\004sign\030\004 \001(\t\"\'\n\tProtoType\022\n\n\006" +
      "SYSTEM\020\000\022\016\n\nNON_SYSTEM\020\001\"-\n\tProtoCode\022\010\n" +
      "\004FAIL\020\000\022\013\n\007SUCCESS\020\001\022\t\n\005ERROR\020\002B\"\n\016proto" +
      "buf.protoB\016WebsocketProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_kcwiki_msgtransfer_protobuf_Websocket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_kcwiki_msgtransfer_protobuf_Websocket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kcwiki_msgtransfer_protobuf_Websocket_descriptor,
        new java.lang.String[] { "ProtoType", "ProtoCode", "ProtoPayload", "Timestamp", "Sign", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
