// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WebsocketSystem.proto

package protobuf.proto;

public interface WebsocketSystemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kcwiki.msgtransfer.protobuf.WebsocketSystem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.kcwiki.msgtransfer.protobuf.WebsocketSystem.SystemMessageType msg_type = 1;</code>
   */
  int getMsgTypeValue();
  /**
   * <code>.kcwiki.msgtransfer.protobuf.WebsocketSystem.SystemMessageType msg_type = 1;</code>
   */
  protobuf.proto.WebsocketSystem.SystemMessageType getMsgType();

  /**
   * <code>string data = 2;</code>
   */
  java.lang.String getData();
  /**
   * <code>string data = 2;</code>
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
