// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WebsocketNonSystem.proto

package protobuf.proto;

public final class WebsocketNonSystemProto {
  private WebsocketNonSystemProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kcwiki_msgtransfer_protobuf_WebsocketNonSystem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kcwiki_msgtransfer_protobuf_WebsocketNonSystem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030WebsocketNonSystem.proto\022\033kcwiki.msgtr" +
      "ansfer.protobuf\"2\n\022WebsocketNonSystem\022\016\n" +
      "\006module\030\001 \001(\t\022\014\n\004data\030\002 \001(\tB+\n\016protobuf." +
      "protoB\027WebsocketNonSystemProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_kcwiki_msgtransfer_protobuf_WebsocketNonSystem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_kcwiki_msgtransfer_protobuf_WebsocketNonSystem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kcwiki_msgtransfer_protobuf_WebsocketNonSystem_descriptor,
        new java.lang.String[] { "Module", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
