// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WebsocketSystem.proto

package kcwiki.msgtransfer.protobuf.proto;

public final class WebsocketSystemProto {
  private WebsocketSystemProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kcwiki_msgtransfer_protobuf_WebsocketSystem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kcwiki_msgtransfer_protobuf_WebsocketSystem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025WebsocketSystem.proto\022\033kcwiki.msgtrans" +
      "fer.protobuf\"\343\002\n\017WebsocketSystem\022P\n\010msg_" +
      "type\030\001 \001(\0162>.kcwiki.msgtransfer.protobuf" +
      ".WebsocketSystem.SystemMessageType\022\014\n\004da" +
      "ta\030\002 \001(\t\"\357\001\n\021SystemMessageType\022\017\n\013SYSTEM" +
      "_INFO\020\000\022\r\n\tDEBUG_MSG\020\001\022\021\n\rPAYLOAD_ERROR\020" +
      "\002\022\021\n\rCLIENT_REBOOT\020\003\022\023\n\017CLIENT_SHUTDOWN\020" +
      "\004\022\021\n\rSERVER_REBOOT\020\005\022\023\n\017SERVER_SHUTDOWN\020" +
      "\006\022\032\n\026AUTHORIZATION_REQUIRED\020\007\022\026\n\022AUTHORI" +
      "ZATION_FAIL\020\010\022\031\n\025AUTHORIZATION_SUCCESS\020\t" +
      "\022\010\n\004PING\020\nB;\n!kcwiki.msgtransfer.protobu" +
      "f.protoB\024WebsocketSystemProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_kcwiki_msgtransfer_protobuf_WebsocketSystem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_kcwiki_msgtransfer_protobuf_WebsocketSystem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kcwiki_msgtransfer_protobuf_WebsocketSystem_descriptor,
        new java.lang.String[] { "MsgType", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
