// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WebsocketWapper.proto

package kcwiki.msgtransfer.protobuf.proto;

public final class WebsocketWapperProto {
  private WebsocketWapperProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kcwiki_msgtransfer_protobuf_WebsocketWapper_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kcwiki_msgtransfer_protobuf_WebsocketWapper_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025WebsocketWapper.proto\022\033kcwiki.msgtrans" +
      "fer.protobuf\"\271\002\n\017WebsocketWapper\022J\n\nprot" +
      "o_type\030\001 \001(\01626.kcwiki.msgtransfer.protob" +
      "uf.WebsocketWapper.ProtoType\022J\n\nproto_co" +
      "de\030\002 \001(\01626.kcwiki.msgtransfer.protobuf.W" +
      "ebsocketWapper.ProtoCode\022\025\n\rproto_payloa" +
      "d\030\005 \001(\014\022\021\n\ttimestamp\030\003 \001(\003\022\014\n\004sign\030\004 \001(\t" +
      "\"\'\n\tProtoType\022\n\n\006SYSTEM\020\000\022\016\n\nNON_SYSTEM\020" +
      "\001\"-\n\tProtoCode\022\010\n\004FAIL\020\000\022\013\n\007SUCCESS\020\001\022\t\n" +
      "\005ERROR\020\002B;\n!kcwiki.msgtransfer.protobuf." +
      "protoB\024WebsocketWapperProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_kcwiki_msgtransfer_protobuf_WebsocketWapper_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_kcwiki_msgtransfer_protobuf_WebsocketWapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kcwiki_msgtransfer_protobuf_WebsocketWapper_descriptor,
        new java.lang.String[] { "ProtoType", "ProtoCode", "ProtoPayload", "Timestamp", "Sign", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
