// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WebsocketWapper.proto

package kcwiki.msgtransfer.protobuf.proto;

public interface WebsocketWapperOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kcwiki.msgtransfer.protobuf.WebsocketWapper)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.kcwiki.msgtransfer.protobuf.WebsocketWapper.ProtoType proto_type = 1;</code>
   */
  int getProtoTypeValue();
  /**
   * <code>.kcwiki.msgtransfer.protobuf.WebsocketWapper.ProtoType proto_type = 1;</code>
   */
  kcwiki.msgtransfer.protobuf.proto.WebsocketWapper.ProtoType getProtoType();

  /**
   * <code>.kcwiki.msgtransfer.protobuf.WebsocketWapper.ProtoCode proto_code = 2;</code>
   */
  int getProtoCodeValue();
  /**
   * <code>.kcwiki.msgtransfer.protobuf.WebsocketWapper.ProtoCode proto_code = 2;</code>
   */
  kcwiki.msgtransfer.protobuf.proto.WebsocketWapper.ProtoCode getProtoCode();

  /**
   * <code>bytes proto_payload = 5;</code>
   */
  com.google.protobuf.ByteString getProtoPayload();

  /**
   * <code>int64 timestamp = 3;</code>
   */
  long getTimestamp();

  /**
   * <code>string sign = 4;</code>
   */
  java.lang.String getSign();
  /**
   * <code>string sign = 4;</code>
   */
  com.google.protobuf.ByteString
      getSignBytes();
}
